In [1]:
import numpy as np
import pandas as pd
import sklearn.datasets

In [2]:
breast_cancer = sklearn.datasets.load_breast_cancer()

In [3]:
x = breast_cancer.data
y = breast_cancer.target

In [6]:
x[0:1]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]])

In [7]:
y[0:1]

array([0])

In [8]:
data = pd.DataFrame(breast_cancer.data, columns=breast_cancer.feature_names)

In [9]:
data['class'] = breast_cancer.target

In [10]:
data.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  class  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [11]:
print(data['class'].value_counts())

1    357
0    212
Name: class, dtype: int64


In [12]:
from sklearn.model_selection import train_test_split


In [13]:
x = data.drop('class', axis=1)
y = data['class']

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.1)

In [15]:
print(x.shape, X_train.shape, X_test.shape)


(569, 30) (512, 30) (57, 30)


In [16]:
print(y.shape, Y_train.shape, Y_test.shape)


(569,) (512,) (57,)


In [17]:
x_binarised_train = X_train.apply(pd.cut, bins=2, labels=[1,0])

In [18]:
x_binarised_test = X_test.apply(pd.cut, bins=2, labels=[1,0])

In [19]:
x_binarised_test = x_binarised_test.values
x_binarised_train = x_binarised_train.values

In [20]:
x_binarised_test

array([[1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [0, 1, 0, ..., 0, 1, 1]], dtype=object)

In [23]:
from sklearn.metrics import accuracy_score


In [24]:
class MPNeuron:
    
    def __init__(self):
        self.b = None
    
    def model(self, x):
        return(sum(x) >= self.b)
    
    def predict(self, X):
        Y = []
        for x in X:
            result = self.model(x)
            Y.append(result)
        return np.array(Y)
    
    def fit(self, X, Y):
        accuracy = {}
        
        for b in range(X.shape[1] + 1):
            self.b = b
            Y_pred = self.predict(X)
            accuracy[b] = accuracy_score(Y_pred, Y)
        
        best_b = max(accuracy,key = accuracy.get)
        self.b = best_b
        
        print('Optimal Value of  is', best_b)
        print('Highest accuracy is',accuracy[best_b])

In [25]:
mp_neuron = MPNeuron()
mp_neuron.fit(x_binarised_train, Y_train)

Optimal Value of  is 27
Highest accuracy is 0.857421875


In [26]:
Y_test_pred = mp_neuron.predict(x_binarised_test)
accuracy_test = accuracy_score(Y_test_pred, Y_test)

In [27]:
print(accuracy_test)

0.8596491228070176
